# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Sean Caetano Martin"
tagline:          'xonecas'
description:      "I'm a software engineer who enjoys the ocasional blog post."
url:              http://xonecas.github.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/xonecas
